# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(1, 'Enabled'), (9, 'Disabled')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_stops', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_know_stop', models.IntegerField(default=0)),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Beacon')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Route')),
            ],
        ),
    ]
